# Workflow name
name: Deploy to GitHub Pages

# Trigger the workflow on pushes to the 'main' branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

# Define a single job for deployment
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    # REQUIRED: Grant the GITHUB_TOKEN write permissions
    permissions:
      contents: write

    # Steps for the job
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Step 2: Setup Node.js 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Deploy the static files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
          force_orphan: true